### ISSUE TITLE
Upgrade GHC version in tests?

### ISSUE THREAD

**Issue by Xe** [TokTok/hstox#41]
GHC 7.8 is kind of old, a significant amount of the community and libraries I use have moved to 7.10.3. Does this work in 7.10.3?

**Comment by iphydf** [comment]
Yes, I develop it on 7.10.3, and it also works on 8.0.1 (the Android build uses that). It also works on 7.6.4, after #37 is merged.

**Comment by Xe** [comment]
Oh nice, is there any example code available?

**Comment by iphydf** [comment]
What would you like to see an example of?

**Comment by Xe** [comment]
- Establish connection
- Iterate over incoming messages

**Comment by iphydf** [comment]
At the moment, the Haskell protocol implementation is very basic. There is no networking yet. The first step is to write tests that run against the C implementation, and write a Haskell model implementation that produces the same results. This is what we are working on at the moment.

In an [old version](https://github.com/TokTok/hstox/blob/a8e89fb3028bcff8e111fd331e06847a0f37398c/src/Network/NetworkSpec.hs) there was a network test that connects to the DHT and does some query. Now we are focussing on making the functional part work.

**Comment by iphydf** [comment]
Is there anything actionable here? Is your suggestion to test hstox against 7.10.3 on travis? I'm not sure the haskell environment actually has 7.10.3, so it would involve getting the compiler from hvr-ghc.

**Comment by iphydf** [comment]
@Xe, the ffi branch in PR #62 will give you the ability to implement groupbot or anything else tox-related in Haskell. The FFI is not completely done yet, and contributions are welcome :).
